### ISSUE TITLE
CSS for default RT

### ISSUE THREAD

**Issue by DjamZee** [p4535992/foundryvtt-better-rolltables#10]
Hi P, I missed your answers on my last issue. What i meant was for the defaut rolltable. As you can see, there is something wierd with the text color and the backgrond of the Table. It would be nice if your default BRT rolltable dont overide the default rolltable of the system. I dont know if i am understandable XD

Default roll table sheet of my system (Custom Shadowrun 5)
![RT défaut](https://github.com/p4535992/foundryvtt-better-rolltables/assets/118370712/d9cd9295-6635-49a8-bfa3-b7e0e65d528a)

Default roll table sheet with BRT
![BRT Deflaut](https://github.com/p4535992/foundryvtt-better-rolltables/assets/118370712/0f049c93-c4a3-486e-aa09-900d56d458f4)

**Comment by Mstanic05** [comment]
Can you assign this to me!

**Comment by p4535992** [comment]
i removed the css backgrund by default
