### ISSUE TITLE
[BUG] Does not work in Foundry

### ISSUE THREAD

**Issue by OrangeBlueHue** [p4535992/foundryvtt-better-rolltables#14]
**Module Version:** v2.0.29

**Before open any issue**

1) Enable the module setting _"Enable debugging"_
2) Click F12 go to the _console_ tab 
3) make the test you want and replicate the error
4) Go to the tab console open on point 2) and just right click and click 'Save as' and 'Save' or send a screenshot of the exception on the console.
5) Attach the text file on the github issue with all the logs related tot he module, or send a screenshot of the messages on the console.

**Describe the bug**
Simply does not work. Does not work in any system. Does not work when it is only this module (plus dependencies). The rolltables are the default rolltables and have zero reference to the module in any way shape or form. The compendiums are present, but the tables are the default.

**To Reproduce**
Don't know how.

**Expected behavior**
It is supposed to work.

**Foundry Version:** 
11 Build 314

**Game System:** 
Mythras, DnD 5e

**Comment by p4535992** [comment]
- Enable the module setting "Enable debugging"
- Click F12 go to the console tab
make the test you want and replicate the error
- Go to the tab console open on point 2) and just right click and click 'Save as' and 'Save' or send a screenshot of the exception on the console.
- Attach the text file on the github issue with all the logs related tot he module, or send a screenshot of the messages on the console.

**Comment by OrangeBlueHue** [comment]
This is the only kind of issue I can find. 

**DEBUG | better-rolltables | Set table type to null for default sheet rolltable config
Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform**

There are no indications that the module is even active or doing anything aside from the compendiums.
You mentioned browser, is this a browser only thing? I'm using the FoundryVTT program

**Comment by p4535992** [comment]
Sorry about the mix up, maybe we don't understand each ohter , can you confirm you didn't see these voices ?

![](https://i.imgur.com/OAqcWAE.png)

**Comment by OrangeBlueHue** [comment]
Well now I feel foolish. Yeah it's all there now, I did not realize I needed to set the sheets like that. I apologize for wasting your time.

**Comment by p4535992** [comment]
np i must find the time to enrich the docucmentation
