### ISSUE TITLE
[BUG][Pf2e Integration] when I [Gen.Token] to a merchant actor the quanties and bulks are messed up

### ISSUE THREAD

**Issue by Strangley-Browne** [p4535992/foundryvtt-better-rolltables#15]
**Module Version:** v2.0.31
**Browser:** Chrome
**Foundry Version:** 315
**Game System:** Pathfinder 2e 5.9.5

When I use [Gen. Token] with a Merchant actor the quanity and bulk of an item are not sent? NaN? (after the first one is generated).
This is in a new world with no other modules loaded
No errors in console
![image](https://github.com/p4535992/foundryvtt-better-rolltables/assets/87890230/e9b050c9-744c-410a-9f79-0e22249fa4a1)

**Comment by p4535992** [comment]
Try out 2.1.0 and let me know it if the issue persist.
