### ISSUE TITLE
[BUG] Generate Rolltable with Filters

### ISSUE THREAD

**Issue by lukekostrewa** [p4535992/foundryvtt-better-rolltables#16]
**Module Version:** v2.0.31

I've been trying to get the Spell Scroll generation with a random spell but can't seem to get it to work.
I then tried to create a rolltable with filters but got the error saying no compendium was found.
It does work when I generate a rolltable without filters so the compendium is working properly

My compendium:
![20231212120438](https://github.com/p4535992/foundryvtt-better-rolltables/assets/152325522/cb6e5a03-ee27-43f8-a9dd-1ac3ca1e4612)

After Right clicking I get this menu and the "BRT Generate rolltable." works perfectly fine:
![20231212120502](https://github.com/p4535992/foundryvtt-better-rolltables/assets/152325522/fec8e866-d9f8-4e42-a1e1-14f66a9cf9f7)

The last option to generate with filters gives me this error:
![20231212120636](https://github.com/p4535992/foundryvtt-better-rolltables/assets/152325522/be1cc070-0edc-493e-9652-0c2318ba9c96)

I also have issues with the Spell Scroll generation but I don't get error messages with that one, it just doesn't do anything

**Comment by p4535992** [comment]
Should  be finally fixed on 2.0.32

**Comment by mnoreke** [comment]
This remains as an issue.
![image](https://github.com/p4535992/foundryvtt-better-rolltables/assets/5225366/cbfa1572-2c08-4c59-97fa-c3baee1dcf26)

**Comment by p4535992** [comment]
Strange i was sure was solved... i will check out with that compendium
