### ISSUE TITLE
GM Only Table is visible for players. [BUG]

### ISSUE THREAD

**Issue by Vishara** [p4535992/foundryvtt-better-rolltables#17]
Hey there =)

im using your addon for hiding the rolls from a table from the players.
But it seems like the GM Only option is not working anymore? 

Ive tested it for my existing table and a new one. In both cases a trusted player can see the roll an this will make the table for my case unuseable (I want to create a random encounter for the camp in the night)

Im using the "better table" table.
![image](https://github.com/p4535992/foundryvtt-better-rolltables/assets/10507584/3002c37e-09cb-4edd-964b-d71f3f73dd91)

![image](https://github.com/p4535992/foundryvtt-better-rolltables/assets/10507584/45b3d792-58b7-4575-8a43-909ebbf93e1c)

It definitly worked in the past. But then I updated every module, and the game system (dnd5e) and it is broken for me. 
Last update was around 1 or 2 months.
![image](https://github.com/p4535992/foundryvtt-better-rolltables/assets/10507584/e7170ac1-fefc-4402-9406-7ecbf2b584b2)
![image](https://github.com/p4535992/foundryvtt-better-rolltables/assets/10507584/ec32b924-5543-401e-8740-5d39ef46c581)

Perhaps something broke with the update?

**Comment by p4535992** [comment]
Tested to be sure, seems to be working, is the GM rolling the rolltabe or the player  ? If the "hidden table" is checked  It is impossible for the trusted player to see the message is directed only to GMs in fact the way it is written in the chat card. If the "XXX" player sees it in the chat card there should be a reference to "XXX".

**Comment by p4535992** [comment]
Didn't test on 2.4.1 tough.... but nothing should be change on the chat card creation behaviour

**Comment by Vishara** [comment]
Very strange ... 
I tested it this morning again. And now its working again >.<

I dont know why, because I litterally just loaded the world (No updates or similar)
The pictures from yesterday, was created from the GM Player and the rolled card, from a spectator "trusted player". So it was both on the same machine. But even a player in the network have seen the results ... 

But now? It seems to work again. 
Im really confused. 

I feel like windows and "have you tried turn off and on again?" xD
