### ISSUE TITLE
Is there a way to from a rolltable to call another roll table and have it roll 4d4 times? 

### ISSUE THREAD

**Issue by LuvacZantor** [p4535992/foundryvtt-better-rolltables#20]
Is there a way to from a rolltable to call another roll table and have it roll 4d4 times?

**Comment by p4535992** [comment]
Hi sorry for the delay, the use case you told me is very general, but to roll an inner (or child ) rolltable 4d4 times of you just need to set in the quanity field the string "4d4" and an amount roll of at least 1.
