### ISSUE TITLE
[BUG]Harvest Table with Skill Dc doesnt work

### ISSUE THREAD

**Issue by Maradeurfv** [p4535992/foundryvtt-better-rolltables#21]
**Module Version:** v2.0.31

**Before open any issue**

Harvest Table, Rolls mith DC and Skill doesnt work. No DC is checked before the roll.

**Browser:**
 - Chrome

**Foundry Version:** Latest

**Game System:** DnD5e

**Comment by p4535992** [comment]
Seem to work . Did you use the API or the standard UI ? Can you exprot to me the rolltable ?
