### ISSUE TITLE
Nested Loot Generation [BUG]

### ISSUE THREAD

**Issue by jknolte** [p4535992/foundryvtt-better-rolltables#26]
Loot generated to Actors and to Tokens via BRT appears to create additional quantities when nested rolltables are used. Rolltable quantities, either numerical or dice expressions, don't seem to work with loot generated to actors/tokens.

**Steps to reproduce:**
Step 1:
In a fresh Foundry world with only Better Rolltables installed, create a Better Rolltable with a table nested inside it:
![image](https://github.com/p4535992/foundryvtt-better-rolltables/assets/159180002/35b043eb-e625-476e-baca-5fd21b4174c8)
Screenshot of the nested table for example:
![image](https://github.com/p4535992/foundryvtt-better-rolltables/assets/159180002/e386724c-22c9-4a19-be80-ffe6cb17ad7c)

Step 2:
Use the rolltable that contains the nested rolltable to generate loot on a Token or an Actor.

Step 3:
Observe that the quantity of items rolled may not match the expected result.

Below, I rolled the "Test Bettertable" from the screenshot to generate to this token, and the token received 3 Beads of Force and 1 Adamantine Scale Mail, which should not be possible. The token should have received a single item from the "Nested Table Test" screenshotted above, but it received 4 total items:
![image](https://github.com/p4535992/foundryvtt-better-rolltables/assets/159180002/6b73b0dc-acb5-402f-a90e-2f4b5f12324f)

Log of messages from console when Generate Loot to Token was pressed:
[better-rolltablesLoot generation.txt](https://github.com/p4535992/foundryvtt-better-rolltables/files/14184653/better-rolltablesLoot.generation.txt)

**Comment by p4535992** [comment]
Try out 2.1.0 and let me know it if the issue persist

**Comment by jknolte** [comment]
looks to be fixed, thanks!
