### ISSUE TITLE
[Feature] Auto roll dice with inline text

### ISSUE THREAD

**Issue by rednek74** [p4535992/foundryvtt-better-rolltables#27]
I am not sure if this is already done but I can't seem to find anything that works with in the loot table to get it to roll say 2d4 and give me a result inline. I have tried multiple formulas that I have seen in your screen shots but I don't want currency. I have looked at other tables that have been imported from books and tried to use that but can't get it to work either. I have tried {2d4} [[2d4]] ([[r/ 2d4]]) and I just can't seem to get it to work right.

**Comment by p4535992** [comment]
Add something, but i'm not sure if is what you want...
Start a new tutorial documentation with examples here : https://github.com/p4535992/foundryvtt-better-rolltables/blob/master/wiki/Home.md
