### ISSUE TITLE
[BUG] Better roll tables is preventing Media Optimizer from converting media files

### ISSUE THREAD

**Issue by theripper93** [p4535992/foundryvtt-better-rolltables#28]
BRT: 2.0.34
FVTT: V11.315
System (irrelevant) dnd5e 3.0.2
Media Optimizer (any version)
All other modules disabled.

For unknown reasons, when Better Roll Tables is enabled, the dynamic import for the FFMPEG module that media optimizer uses fails

```js
    await import("https://unpkg.com/@ffmpeg/ffmpeg@0.10.0/dist/ffmpeg.min.js");
    const createFFmpeg = FFmpeg.createFFmpeg;
```
After the import it's expected a `window.FFmpeg` - if BRT is enabled this is undefined.

**Comment by p4535992** [comment]
I've tried recreating the issue, but to no avail, I've generally had these problems on aplications hosted on the forge, I've cleaned up a lot of code with 2.1.0 let me know if the issue persists.
