### ISSUE TITLE
[Feature Request] Chronicles of Darkness 2.0

### ISSUE THREAD

**Issue by RinVindor** [p4535992/foundryvtt-better-rolltables#29]
https://gitlab.com/MarlQ/mta/-/releases/0.13.0

CofD 2.0 just added item quantities to the sheets so I'm hoping we could have support from BRT. Love this mod a ton for D&D and I'm looking forward to making use of the tons of macros and tables I've built up for CofD as well! Thanks for the hard work!

**Comment by p4535992** [comment]
This module relies from 2.1.x directly on item piles, so you should integrate the configuration file for your system for that module and BRT functionality will already be available.
