### ISSUE TITLE
Regarding tables that are hidden from Players

### ISSUE THREAD

**Issue by YenBenGrey** [p4535992/foundryvtt-better-rolltables#3]
Hello there, 

I have only just started getting in to rolltables, and boy have I been missing out. 

When I create a table and include another rolltable within that roll table and set to hidden, the result's name is hidden but not the picture.
Fair enough I can change the picture to something non-relating however just wondered if this was something that can be dealt with regarding the hidden feature?

I am sure you can see which one is the DM view and the one that is the player view. 

![image](https://github.com/p4535992/foundryvtt-better-rolltables/assets/98095856/e51aa04a-594f-4476-a99c-603847a12234)
![image](https://github.com/p4535992/foundryvtt-better-rolltables/assets/98095856/cff90502-5db3-40d6-8005-e908f13e6a30)

**Comment by p4535992** [comment]
What system are you using ? i cannot replicate the "hidden" text behavior

**Comment by YenBenGrey** [comment]
I am using DND5e

Regarding the hidden feature, there was a setting in the table to hide it, but I can't see it anymore.

**Comment by p4535992** [comment]
Don't you see the check box on the header section of the sheet table ?

![](https://i.imgur.com/ifFUJRa.png)

**Comment by YenBenGrey** [comment]
Oh wait, the options to choose what sheet to use is in the sheet drop down, that has moved recently? 

I am currently on the default sheet. 

But if I hide the sheet and then add that sheet to another table and that tables result is to roll on the hidden table then the text hidden appears but also the picture of whatever the hidden text is.

**Comment by YenBenGrey** [comment]
I think I might have to read up on all your updates, I only started using BRT about a week ago ha ha :-)

**Comment by YenBenGrey** [comment]
OK so just done some more testing and this time, even though the other table is set to hidden, the result wasn't hidden from the player. 

I think what I am looking for is that they roll on a master table, and they see the very basics so for example on this table which is Coastal Encounters Daytime - 
1-50 is just sand and sea everywhere. 
then one of the other results is Coastal Monsters, and that rolls on another table, and for the player ideally they should just see something like "Encounter" or "Event" and I see "Orc" or "Goblin" or whatever monster the other table brings up. 

Hope that makes some kind of sense.

**Comment by YenBenGrey** [comment]
Update Update....

I have updated to the latest BRT and I have a potential problem, but it could be the way I am settings things up. 

I have a rolltable called Bamboo Forest. The Players can roll on it from a macro.

Within this rolltable there is a potential to get a random monster encounter, this is a separate rolltable that the results are hidden from the players, however when they roll on the Bamboo Forest table and get the random monster table, they see the result of the monster table. And can even click on the monster in the chat. :-/
