### ISSUE TITLE
Not sure if this is a request or a bug..BRTs within BRTs

### ISSUE THREAD

**Issue by YenBenGrey** [p4535992/foundryvtt-better-rolltables#30]
Hello there,

When a put another BRT within another BRT, and then the original BRT rolls and it is the BRT within the BRT, it does not roll the amount of things that it comes up with. 

I am finding it difficult to explain this, so if I have a BRT of random Wilderness events and one is a random monster BRT, when the Monster BRT rolls and comes up with for example rats, and in the BRT it is set to 1d20 rats, it doesn't roll the amount.

**Comment by p4535992** [comment]
it's was a bug, i completely forgot to test the new code for this use case. Try out 2.1.5 and let me know it

**Comment by YenBenGrey** [comment]
I have sent a DM in Discord. It works from the roll table directly but I use macros. The DM will explain better.

**Comment by p4535992** [comment]
K i readed the discord comment it's seem a request for a comaptibility module with dice so nice.
I'll close this ticket
