### ISSUE TITLE
Players are not able to use the BRT (Quick Acces Button) and normal Roll+ Button [BUG]

### ISSUE THREAD

**Issue by The-VoyZ** [p4535992/foundryvtt-better-rolltables#32]
Hey I dont get the BRT rolltables to work for my Players. I dont know why. Especially the button that you can set in the settings for a quicker access for players and my self (For me it works but for my players it doesn't)
Even if i give my Players the Observer Rights they are not able to Click on the Roll+ Button strait in the sheet) Only if i give them Owner Rights.
I turned on debugging mode and didnt got any output or errors.

**Comment by p4535992** [comment]
Try out version 2.1.8 and let me know it

**Comment by SR11980140** [comment]
Seems broken again. I'm having the same problem now.
BRT Version 12.0.1
FVTT version 12.331
