### ISSUE TITLE
[BUG] Can't see roll results as GM if table is marked as `hidden`

### ISSUE THREAD

**Issue by ctbritt** [p4535992/foundryvtt-better-rolltables#34]
**Module Version:** v2.1.9

**Before open any issue**

1) Enable the module setting _"Enable debugging"_
2) Click F12 go to the _console_ tab 
3) make the test you want and replicate the error
4) Go to the tab console open on point 2) and just right click and click 'Save as' and 'Save' or send a screenshot of the exception on the console.
5) Attach the text file on the github issue with all the logs related tot he module, or send a screenshot of the messages on the console.

**Describe the bug**
When making a BRT roll on a Better Roll Table, if the table is marked as `hidden` even the GM can't see the result. 

**To Reproduce**
1. Click "Hidden table" in the BRT settings
2. Click Roll+
3. The chat log shows an obscured icon and ??? for the result in in the chat log
4. Console produces error

**Expected behavior**
The result of the roll should be presented the GM but not to players.

**Screenshots**
![CleanShot 2024-03-23 at 23 20 06@2x](https://github.com/p4535992/foundryvtt-better-rolltables/assets/4516034/fcb32d25-0ff9-4ab4-b2fd-cca7a83fde90)
(Error message in Console)
![CleanShot 2024-03-23 at 23 23 35@2x](https://github.com/p4535992/foundryvtt-better-rolltables/assets/4516034/da91ac84-1e33-4fe2-8be2-1eb8605fc0d4)
(Chat result when clicking Roll+ button)
![CleanShot 2024-03-23 at 23 24 02@2x](https://github.com/p4535992/foundryvtt-better-rolltables/assets/4516034/7a2823c9-1aee-4229-b9bd-aafe043d468b)
Result when clicking "Roll" button. Not hidden from players.

**Browser:**
 - Chrome 123.0.6312.59

**Foundry Version:** 
11.315
**Game System:** 
DnD5e 3.1

**Additional context**
This happens with just Libwrapper, socketlib, BRT and ItemPiles active.

**Comment by p4535992** [comment]
Ty for the detailed ticket, it should be solved on 2.1.10, or at least it seem to work to me. If the issue persist i need a copy of the rolltables .

**Comment by ctbritt** [comment]
Thank you for the fix, but it seems like it's an issue with tables that have rolled numbers in the text field. A table this like also shows the "???" card when Roll+ is clicked: 
![CleanShot 2024-03-24 at 19 52 46](https://github.com/p4535992/foundryvtt-better-rolltables/assets/4516034/8eb45368-6fe3-406e-90c7-b115cd30f5d8)

**Comment by p4535992** [comment]
try out 2.1.11, should be fixed now

**Comment by ctbritt** [comment]
yes! Works great, thank you!
