### ISSUE TITLE
[BUG] BRT buttons not showing up in the Rolltables sidebar Tab

### ISSUE THREAD

**Issue by jendives2000** [p4535992/foundryvtt-better-rolltables#6]
**Module Version:** v2.0.18

**Before open any issue**

1) Enable the module setting _"Enable debugging"_
2) Click F12 go to the _console_ tab 
3) make the test you want and replicate the error
4) Go to the tab console open on point 2) and just right click and click 'Save as' and 'Save' or send a screenshot of the exception on the console.
5) Attach the text file on the github issue with all the logs related tot he module, or send a screenshot of the messages on the console.

**Describe the bug**
The buttons that are supposed to be added to the Rolltables sidebar tab are not there. 

**To Reproduce**
I just installed the module from the Forge module page. I'm using the Forge. 
I even uninstalled the module, stopped the Forge server, reinstalled it and re-enabled it within Foundry. Still no buttons. 

**Expected behavior**
I should have had the buttons showing up in the Rolltables Sidebar tab. 

**Screenshots**
![image](https://github.com/p4535992/foundryvtt-better-rolltables/assets/94803007/010ec50e-e819-4355-907a-8f7637023a95)

**Browser:**
 - Version 117.0.5938.150 (Official Build) (64-bit)

**Foundry Version:** 
V11 stable 313

**Game System:** 
Dnd 5e 2.3.1

**Additional context**
Here's a list of all modules installed :

Core Version: 11.313

System: dnd5e 2.3.1 (Atropos) 

Modules: 
ATL 0.7.0 (Kandashi, kaelad)
AceEditorVTT 0.3.0 ()
LockView 1.5.8 (CDeenen)
MC5e 11.1.3 (Monkeyy)
Rideable 2.12.6 (saibot)
SupersHomebrewPack 3.0.0 (SuperNar3k)
_chatcommands 2.0.1 (Cody Swendrowski, The League of Extraordinary FVTT Developers, Adrian Haberecht)
action-pack 11.2 (Tero Parvinen (tero.p))
adv-reminder 3.2.1 (kaelad)
advanced-macros 2.0.4 (mclemente, p4535992)
adventuremusic 1.2.1 ()
aedifs-tactical-grid 1.15.1 (Aedif)
allies-and-antagonists 1.1.0 (Grim Press)
always-hp 11.07 (IronMonk)
animated-spell-effects 0.6.8 (Jack Kerouac)
animated-spell-effects-cartoon 0.4.5 ()
archon 1.2.1 (badgerwerks)
autoanimations 4.2.67 (Otigon (Otigon#2010))
autocomplete-inline-properties 2.9.1 (Cole Schultz, Johannes Loher)
automated-evocations 2.0.3 (theripper93)
autorotate v1.3.16 (Varriount)
babonus 11.4.0 (Zhell)
baileywiki-city-district-01 0.2.0 (Baileywiki)
baileywiki-maps-premium-towns 0.4.12 (Baileywiki)
baileywiki-nuts-and-bolts 0.2.2 (Baileywiki)
beavers-crafting 3.2.4 (angryBeaver)
beavers-system-interface 2.1.4 (angryBeaver)
better-rolltables 2.0.18 (Ultrakorne, Daniel Böttner, Daimakaicho, elizeuangelo, sasquach45932, p4535992)
betterroofs 1.9.2 (theripper93)
bsa-dnd5e 2.0.3 (angryBeaver)
caeora-maps-tokens-assets 2.1.5 (Caeora, Voldemalort)
chat-images 3.2 (bmarian)
chat-portrait 0.9.3 (Shoyu Vanilla, p4535992)
chris-premades 0.7.35 (Chris, Autumn)
class-pages 11.1.2 (Zhell)
colorsettings 2.9.1 (ardittristan#0001)
combat-tracker-dock 2.5.1 (theripper93)
compendium-folders 2.6.1 (Erceron)
conversation-hud 5.1.0 (Saervicus (Cristian Vasile))
dae 11.0.18 (tposney)
damage-log 1.16.0 (Alan Davies)
ddb-importer 3.4.77 (MrPrimate)
df-architect 4.0.0 (flamewave000)
df-chat-enhance 4.1.0 (flamewave000)
df-settings-clarity 3.3.0 (flamewave000)
dfreds-chat-pins 3.0.0 (DFreds)
dfreds-convenient-effects 6.0.0 (DFreds)
dfreds-effects-panel 3.1.0 (DFreds)
dice-calculator 1.5.3 (Asacolips)
dlopen 1.0 (KaKaRoTo (The Forge))
dnd-randomizer 1.0.41 (thetreat)
dnd5e-character-monitor 1.7.2 (enso)
dnd5e-scriptlets 0.14 (tposney)
dndbeyond-br 0.3.24 (MrPrimate, The Forge, D&D Beyond)
dndbeyond-dmg 0.3.20 (MrPrimate, The Forge, D&D Beyond)
dndbeyond-lmi 0.3.1 (MrPrimate, The Forge, D&D Beyond)
dndbeyond-mm 0.3.22 (MrPrimate, The Forge, D&D Beyond)
dndbeyond-motm 0.3.5 (MrPrimate, The Forge, D&D Beyond)
dndbeyond-phb 0.3.21 (MrPrimate, The Forge, D&D Beyond)
dndbeyond-tcoe 0.3.6 (MrPrimate, The Forge, D&D Beyond)
dndbeyond-xgte 0.3.17 (MrPrimate, The Forge, D&D Beyond)
dungeon-draw 2.1.0 (mcglintlock)
dynamic-soundscapes 1.5 (theripper93)
effectmacro 11.0.1 (Zhell)
elevationruler 0.7.2 (caewok)
enhancedcombathud 1.7.9 (theripper93, Mouse0270)
epic-rolls-5e 1.8 (theripper93)
filepicker-plus 3.6 (theripper93)
forge-compendium-browser 1.4.0 (The Forge, IronMonk, KaKaRoTo)
forge-vtt-shared-compendiums-ivan-duch-free-music-collection 1.0 (The Forge)
forien-copy-environment v2.2.0 (Blair McMillan, Forien)
foundry-taskbar 3.6.1 (theripper93)
foundry_community_macros 10.4 (FoundryVTTCommunity)
fxmaster 4.0.2 (Johannes Loher (ghost), Emmanuel Ruaud (U~man))
gAudioBundle-1 3.2 ()
gAudioBundle-2 3.3 ()
gAudioBundle-3 3.2 ()
gAudioBundle-4 3.2 ()
gm-screen 4.0.4 (Andrew Krigline)
healthEstimate 31.6.3 (Matheus Clemente)
hiddensoundtracks 0.1.03 (Kandashi)
hot-pan 11.0.4 (coffiarts)
icon-picker 10.3 (Tero Parvinen (tero.p))
illandril-inventory-sorter 2.1.1 (Joe Spandrusyszyn (illandril))
image-hover 3.0.3 (Eriku)
initiative-double-click 1.7 (Matheus Clemente)
innocenti-loot 1.3.1 (Innocenti)
invisible-tokens-can-see-too 1.1.0 (Martin Soemer)
item-delete-check 10.0.8 (tposney)
item-piles 2.7.16 (Wasp)
jb2a_patreon 0.5.9 (Jules, Ben)
journal-font-scaler 0.0.2 (Syrious)
kctg-common 0.13 (kristkos)
lessfog 0.11.1 (trdischat)
levels 4.2.2 (theripper93)
levelsautocover 1.6 (theripper93)
lib-wrapper 1.12.13.0 (Rui Pinheiro)
link-item-resource-5e 2.1.1 (Andrew Krigline)
lootsheetnpc5e 3.6.1 (Jan Ole Peek | ChalkOne, Daniel Böttner | JackPrince, Charles Miller | Kage, NonstickPanda, Kevin Brammer Striky)
media-optimizer 1.9 (theripper93)
metric-ruler-labels 3.1.7 (Roger)
michaelghelfi 1.4 ()
midi-qol 11.1.3 (tposney)
monks-active-tiles 11.11 (IronMonk)
monks-little-details 11.05 (IronMonk)
monks-sound-enhancements 11.04 (IronMonk)
monks-tokenbar 11.05 (IronMonk)
moulinette-core 11.5.0 (Sven Werlen)
move-that-for-you 1.5.0 (Aedif)
multiface-tiles 1.0.11 (Freeze)
music-d20-sampler 1.0.1 (MusicD20)
narrator-tools 0.79 ()
optional-rules-dnd5e 0.5.2 (NekroDarkmoon)
permission_viewer 11.4 (Matheus Clemente)
pin-cushion 1.9.10 (Cole Schultz, Kandashi, ghost, Evan Clarke, Ethaks, p4535992)
popout 2.14 (KaKaRoTo, Posnet)
potion-crafting-and-gathering 0.7.1 (Action Jay, p4535992)
quick-encounters 1.2.1 (Spetzel)
quick-insert 2.8.3 (Sunspots)
rolltable-requester 1.5.0 (Colin Bate)
scene-packer 2.7.7 (Blair McMillan)
sequencer 3.1.4 (Wasp)
sidebar-macros 0.8.3 (Arcanist)
situational-shortcuts 0.9 (theripper93)
smarttarget 1.0.1 (theripper93)
socketlib 1.0.13 (Manuel Vögele)
soundfxlibrary 1.0.2 (CDeenen)
splatter 3.3.4 (theripper93)
stealthy 3.13.2 (Eligarf)
tagger 1.4.5 (Wasp)
tasteful-tooltips 0.2.0 (Drakonik)
templatemacro 11.0.0 (Zhell)
tension-pool 0063 (SDoehren)
theripper-premium-hub 1.2 (theripper93)
tidbits 1.3 (theripper93)
tidy-ui_game-settings 0.1.52 (sdenec)
tile-scroll 2.2 (theripper93)
times-up 11.0.3 (tposney)
token-attacher v4.5.13 (KayelGee)
token-frames 1.6.3 (volfied, Jay Colson)
tokenhoard 1.0.2 (Caeora, badgerwerks)
tokenmagic 0.6.4.1 (SecretFire, sPOiDar, Zimm, Lozalojo, Moerill, KLO, dev7355608, Mestre Digital, BrotherSharper-Touge, OsiJr)
torch 2.11.0 (Deuce, Lupestro)
traps-trammels-and-triggers 1.0.2 (Grim Press)
visual-active-effects 11.0.5 (Zhell)
vtta-tokenizer 4.2.5 (MrPrimate, Sebastian Will)
vueport 1.1 (KaKaRoTo (The Forge))
wall-height 5.0.3 (theripper93, Ian Murphy, Cole Schultz)
warpgate 1.19.0 (honeybadger)
what-the-flag 1.0.3 (theripper93)
forge-vtt 1.10 ()
forge-vtt-optional 1.1 ()

List generated with Forien's Copy Environment: https://github.com/League-of-Foundry-Developers/foundryvtt-forien-copy-environment

**Comment by p4535992** [comment]
I'm sorry what button did you mean ? i don't remember this module do that

"Create Rolltable" and "Create Fodler" are core and on the top of the sidebar .
The button "Create EasyTable" you see in the old video  is from another module

**Comment by jendives2000** [comment]
I can't find these buttons anywhere. 

So here I create a new table 
![image](https://github.com/p4535992/foundryvtt-better-rolltables/assets/94803007/6f8df8af-5355-4087-8698-3d40f52dae7d)

It does not have the multiple dice roll field or the option to create a Better Table neither. 
![image](https://github.com/p4535992/foundryvtt-better-rolltables/assets/94803007/2cda84c0-1851-422a-b0fd-6e1ea7d20aa6)

**Comment by jendives2000** [comment]
I found how to get it. It is in the Sheet cog icon on the top right corner of the rolltable window. 
If you can mention that in this module Foundry page or in the module Github description or in the FAQ, I think it'll help other guys like me.
 
![image](https://github.com/p4535992/foundryvtt-better-rolltables/assets/94803007/eaf537b5-4186-4125-99ec-73da21814294)

Thanks for this module!

**Comment by p4535992** [comment]
Good for you :)
