### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by DjamZee** [p4535992/foundryvtt-better-rolltables#7]
Hi, i wander if it would be possible to make that BRT do not overide ccs of the system it is installed on ? For consistency ^^

**Comment by p4535992** [comment]
Can you be more specific ? What system ? and what css rule you need i remove ?

**Comment by p4535992** [comment]
i will remove the old css code on the next release

**Comment by p4535992** [comment]
try to remove some css, let me know if the issue persist or give more information about your use case
