### ISSUE TITLE
% chance or items in a table

### ISSUE THREAD

**Issue by gudnyt** [p4535992/foundryvtt-better-rolltables#8]
Might already be a feature I'm just missing. But a % chance for each item on the table ie 100 actors and a % chance they are in a tavern for a patron generator:

1) actor 1  10%
2) actor 2  30%
3) actor 3  40%

**Comment by p4535992** [comment]
Add this feature on 2.0.24 try out and let me know it

**Comment by gudnyt** [comment]
Unable to load the mod getting 
better-rolltables| Spell cache could not be initialized/updated.

**Comment by gudnyt** [comment]
![image](https://github.com/p4535992/foundryvtt-better-rolltables/assets/15527270/072b9f65-94a8-4ac8-9f3c-093b852a5940)

**Comment by gudnyt** [comment]
this is with shadowdark rpg havent checked the others yet

**Comment by p4535992** [comment]
shadow dark rpg has not a supported spell cache. i need the string key of the compendium:
