### ISSUE TITLE
[BUG] Text-type items are not drawn on the chat card

### ISSUE THREAD

**Issue by akshay180492** [p4535992/foundryvtt-better-rolltables#9]
**Module Version:** v2.0.21

> **Before open any issue**
> 
> 1) Enable the module setting _"Enable debugging"_
> 2) Click F12 go to the _console_ tab 
> 3) make the test you want and replicate the error
> 4) Go to the tab console open on point 2) and just right click and click 'Save as' and 'Save' or send a screenshot of the exception on the console.
> 5) Attach the text file on the github issue with all the logs related tot he module, or send a screenshot of the messages on the console.

There is no exception on the console. 

**Describe the bug**

BRT tables do not output Text-type items to chat if rolled.

**To Reproduce**

1. Create a BRT table with only a single Text-type item.
2. Click the 'Roll+' button.
3. Check generated chat message.

**Expected behavior**

Expected behaviour is that any Text-type item will be output to chat via the generated chat message.

**Screenshots**

The chat message is supposed to also say 'Arcane Scroll' in text along with any other rolled item, but it does not.

![image](https://github.com/p4535992/foundryvtt-better-rolltables/assets/94251520/ea9b3c8b-d015-44e3-941c-6725953e39ec)
![image](https://github.com/p4535992/foundryvtt-better-rolltables/assets/94251520/298a80ed-7ed0-4a08-8380-8c4207e255d2)

The default 'Roll' option as opposed to the BRT 'Roll+' option outputs text properly.

![image](https://github.com/p4535992/foundryvtt-better-rolltables/assets/94251520/16bfb50c-ad59-4d75-b794-c72c76edecbd)

Rolling with Roll+ on a table that contains only Text-type items produces a blank chat message.

![image](https://github.com/p4535992/foundryvtt-better-rolltables/assets/94251520/1d596249-f8de-4611-9473-14e840db1dba)
![image](https://github.com/p4535992/foundryvtt-better-rolltables/assets/94251520/f748b1c6-e732-4634-9634-657b701f4890)

**Browser:**

Microsoft Edge

**Foundry Version:** 

v11, Build 307

**Game System:**

Pathfinder 1E, v9.4 

**Additional context**

I checked the **content** section of the generated chat message and it looks like this -

```
<div class="table-draw" data-table-id="vkFv7bv76eKgwsY4"  data-id="vkFv7bv76eKgwsY4">
    <!-- TODO <div class="dice-roll">
    <div class="dice-result">
        <div class="dice-formula">{1d100,1d100}</div>
        <div class="dice-tooltip">
    <section class="tooltip-part">
        <div class="dice">
            <header class="part-header flexrow">
                <span class="part-formula">1d100</span>
                
                <span class="part-total">2</span>
            </header>
            <ol class="dice-rolls">
                <li class="roll die d100">2</li>
            </ol>
        </div>
    </section>
    <section class="tooltip-part">
        <div class="dice">
            <header class="part-header flexrow">
                <span class="part-formula">1d100</span>
                
                <span class="part-total">2</span>
            </header>
            <ol class="dice-rolls">
                <li class="roll die d100">2</li>
            </ol>
        </div>
    </section>

</div>

        <h4 class="dice-total">4</h4>
    </div>
</div>
 -->
    <ol class="table-results">
    </ol>
</div>
```

**Comment by p4535992** [comment]
Should be fixed on 2.0.22
